name: Percy

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

env:
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
  percy:
    name: Visual testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install
      run: yarn install
    - name: Build
      run: yarn build
    - name: Start server and run percy
      run: |
        yarn start &
        sleep 60 &&
        yarn visual
      env:
        PERCY_TOKEN: ${{secrets.PERCY_TOKEN}}

